#! /usr/bin/env bash

set -u -e -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
workspace_dir="${script_dir}/workspace"
venv_dir="${workspace_dir}/venv"

virtualenv -p python3 "${venv_dir}"
source "${venv_dir}/bin/activate"

whisper "${@}"
