#! /usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

set -u -e -o pipefail

workspace_dir="${script_dir}/workspace"
venv_dir="${workspace_dir}/venv"

export XDG_CACHE_HOME="${workspace_dir}/.cache"

virtualenv -p python3 "${venv_dir}"
source "${venv_dir}/bin/activate"

/usr/bin/env bash
